version: "3.2"

services:
  backend:
    build: ./
    container_name: ecargo_container
    working_dir: /eCargo
    tty: True
    command:
      - ./commands/start_${MODE}_serv.sh
    ports:
      - 8010:8000
    volumes:
      - static_content:/eCargo/src/static
      - media_content:/eCargo/src/media
      - ./src:/eCargo/src
      - ./commands:/commands
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:12
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env

  pg_admin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    restart: on-failure
    env_file:
      - .env
    ports:
      - 5000:80
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - backend


volumes:
  static_content: { }
  media_content: { }
  pg_data: { }
  pgadmin_data: { }
  commands: { }