# Generated by Django 3.2.16 on 2023-09-17 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='avatar',
            field=models.ImageField(default='media/avatars/default.png', upload_to='media/avatars'),
        ),
    ]
