# Generated by Django 4.1.7 on 2023-08-24 09:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_alter_useraccount_user_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="useraccount",
            name="user_type",
        ),
    ]
