# Generated by Django 4.1.7 on 2023-08-25 06:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0003_remove_useraccount_user_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userdriverprofile",
            name="user",
        ),
        migrations.AddField(
            model_name="useraccount",
            name="avatar",
            field=models.ImageField(default="default.png", upload_to="media/avatars"),
        ),
        migrations.AddField(
            model_name="useraccount",
            name="birth_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="useraccount",
            name="city",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.DeleteModel(
            name="UserCargoProfile",
        ),
        migrations.DeleteModel(
            name="UserDriverProfile",
        ),
    ]
