# Generated by Django 4.1.7 on 2023-04-05 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cargo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cargo",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cargos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
